### ISSUE TITLE
UI doesn't indicate that the max convolution  kernel size is 9

### ISSUE THREAD

**Issue by arav-agarwal2** [madebyollin/convnet-calculator#2]
As this is a calculator that's found on the internet, I'd suggest either relaxing the constraints on the kernel size or making the max-kernel size locked to 9, if that's the max supported. I'm able to make the max-kernel-size 10 and plus, but the calculation only outputs the result as that if you had 9.

**Comment by madebyollin** [comment]
good point. should be fixed - manually entering larger values will now override the slider limits.
